# Site settings
title: Wadie Assal
email: assalw@gmail.com
description: Personal website for Wadie Assal.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wadie.nl" # the base hostname & protocol for your site
github_username:  assalw

# Build settings
markdown: kramdown


# User settings
username: Wadie Assal
user_title: Developer and SysAdmin
email: assalw@gmail.com
github_username:  assalw
gplus_username:  WadieAssal
linkedin_username: assalw
